### ISSUE TITLE
Add block-link styling for use on Code and Work pages

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/gomakethings#90]
```scss
.link-block {
    color: $color-black;

    &:hover {
        color: $color-gray-dark;
        text-decoration: none;
    }
}

.link-block-styled {
    @extend a;

    .link-block:hover & {
        @extend a:hover; 
    }
}
```
